### ISSUE TITLE
Scoket Time out exception - from last 2 days only

### ISSUE THREAD

**Issue by rrepaka** [paypal/PayPal-Java-SDK#154] opened 2016-02-16 17:32 UTC
I am using Rest API method, it was working fine, But i am seeing socket time out exception from last 2 days

java.net.SocketTimeoutException: Read timed out
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1673)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1671)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1244)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:160)
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:67)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:425)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:267)
	at com.paypal.api.payments.Payment.create(Payment.java:484)

**Comment by pp-randy** [comment] 2016-02-23 21:58
This appears to be a duplicate of https://github.com/paypal/PayPal-Java-SDK/issues/155.  Closing for now, please let me know if this isn't the case.

**Closed by pp-randy** 2016-02-23 21:58 UTC
