### ISSUE TITLE
401 Error while making paypal payment

### ISSUE THREAD

**Issue by viper-pranish** [paypal/PayPal-Java-SDK#217] opened 2016-07-15 11:22 UTC
### General Information

- Mode (Sandbox):
- Version of Java used: 1.8
- SDK Version: 1.8.0

When I am trying to make paypal payment using credit card, I get 401 error response. Lets say yesterday the payment code works fine. But when I run it today, it gives 401 error. 401 is for unauthorized access. But I haven't changes the clientId and clientSecret credentials. 

Paypal method gives me the same access token every time I make the call. When I restart my application, I get a new access token. 

**UPDATE :- ** Now I am having more serious problem. Now I am not even getting a new access token even after restarting my tomcat server.

I get the following error :-

```
response-code: 401  details: null
  at com.paypal.base.rest.PayPalRESTException.createFromHttpErrorException(PayPalRESTException.java:72)
  at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:437)
  at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:292)
  at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:22
  at com.paypal.api.payments.Payment.create(Payment.java:147)
  at com.paypal.api.payments.Payment.create(Payment.java:133)
  at org.ekbana.api.persistence.impl.PaymentServiceImpl.executeSinglePayment(PaymentServiceImpl.java:82)
  at org.ekbana.api.persistence.impl.PurchasedLicenseServiceImpl.executeSinglePayment(PurchasedLicenseServiceImpl.java:276)
  at org.ekbana.api.persistence.impl.PurchasedLicenseServiceImpl.singlePayment(PurchasedLicenseServiceImpl.java:8
  at sun.reflect.GeneratedMethodAccessor818.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:49
  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
  at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
  at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:20
  at com.sun.proxy.$Proxy110.singlePayment(Unknown Source)
  at org.ekbana.payment.controller.web.PaymentController.singlePayment(PaymentController.java:32)
  at sun.reflect.GeneratedMethodAccessor817.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:49
  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:871)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:64
  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.ekbana.payment.context.filter.SecurityFilter.doFilter(SecurityFilter.java:84)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.ekbana.payment.context.filter.CorsFilter.doFilter(CorsFilter.java:29)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:8
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.lang.Thread.run(Thread.java:745)
Caused by: com.paypal.base.exception.HttpErrorException: Response code: 401  Error response: Server returned HTTP response code: 401 for URL: https://api.sandbox.paypal.com/v1/payments/payment
  at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:162)
  at com.paypal.base.HttpConnection.execute(HttpConnection.java:65)
  at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:423)
  ... 63 more
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.sandbox.paypal.com/v1/payments/payment
  at sun.reflect.GeneratedConstructorAccessor225.newInstance(Unknown Source)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890)
  at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885)
  at java.security.AccessController.doPrivileged(Native Method)
  at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
  at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
  at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:132)
  ... 65 more
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.sandbox.paypal.com/v1/payments/payment
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
  at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
  at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:33
  at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:117)
  ... 65 more
ERROR 2016-07-15 10:25:47,951 [PurchasedLicenseServiceImpl] org.ekbana.api.persistence.impl.PurchasedLicenseServiceImpl:281 - PaymentService.singlePayment()
DEBUG 2016-07-15 10:25:47,951 [PurchasedLicenseServiceImpl] org.ekbana.api.persistence.impl.PurchasedLicenseServiceImpl:282 - Exception : 
org.ekbana.api.handler.exceptions.ApiException
  at org.ekbana.api.persistence.impl.PaymentServiceImpl.executeSinglePayment(PaymentServiceImpl.java:92)
  at org.ekbana.api.persistence.impl.PurchasedLicenseServiceImpl.executeSinglePayment(PurchasedLicenseServiceImpl.java:276)
  at org.ekbana.api.persistence.impl.PurchasedLicenseServiceImpl.singlePayment(PurchasedLicenseServiceImpl.java:8
  at sun.reflect.GeneratedMethodAccessor818.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:49
  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
  at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
  at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:20
  at com.sun.proxy.$Proxy110.singlePayment(Unknown Source)
  at org.ekbana.payment.controller.web.PaymentController.singlePayment(PaymentController.java:32)
  at sun.reflect.GeneratedMethodAccessor817.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:49
  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:871)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:64
  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.ekbana.payment.context.filter.SecurityFilter.doFilter(SecurityFilter.java:84)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.ekbana.payment.context.filter.CorsFilter.doFilter(CorsFilter.java:29)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:8
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.lang.Thread.run(Thread.java:745)
ERROR 2016-07-15 10:25:48,015 [RestException] org.ekbana.api.handler.exceptions.RestException:183 - ValidationErrorf      444444
org.ekbana.api.handler.exceptions.ValidationException
  at org.ekbana.api.persistence.impl.PurchasedLicenseServiceImpl.executeSinglePayment(PurchasedLicenseServiceImpl.java:284)
  at org.ekbana.api.persistence.impl.PurchasedLicenseServiceImpl.singlePayment(PurchasedLicenseServiceImpl.java:8
  at sun.reflect.GeneratedMethodAccessor818.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:49
  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
  at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
  at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:20
  at com.sun.proxy.$Proxy110.singlePayment(Unknown Source)
  at org.ekbana.payment.controller.web.PaymentController.singlePayment(PaymentController.java:32)
  at sun.reflect.GeneratedMethodAccessor817.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:49
  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:871)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:64
  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.ekbana.payment.context.filter.SecurityFilter.doFilter(SecurityFilter.java:84)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.ekbana.payment.context.filter.CorsFilter.doFilter(CorsFilter.java:29)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:8
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by jaypatel512** [comment] 2016-07-15 15:11
Hey @viper-pranish !

Btw, v1.8.0 was followed with v1.9.0, which included few more bug fixes that may not be affecting you, but it would be nice to get to the latest version. 

In your case, getting only one access token is expected, as we now cache the access token till it is expired. You can reuse the access token multiple times without any issues.

About the error you are getting, can you please add some code snippet to realize how you are implementing the code ? This should help us determine if there is something wrong there.

**Comment by jaypatel512** [comment] 2016-07-18 18:33
Hey @viper-pranish !

Were you able to resolve the issue ?  Here is a [quick start guide](https://github.com/paypal/PayPal-Java-SDK/wiki/Making-First-Call) to make sure on how you are initializing APIContext.

I will close this issue for now, but do feel free to re-open if this is not the resolution to your issue. I would be more than happy to help you on it ASAP.

**Closed by jaypatel512** 2016-07-18 18:33 UTC
Labels: question

**Comment by twiho** [comment] 2016-10-27 14:25
Hi @jaypatel512, we've recently upgraded our sdk from 1.4.1 to 1.11.0 and it seems like after the update we're getting 401s without making any changes to the credentials.

We get the ApiContext in this fashion:
```
APIContext apiContext = new APIContext(bearerToken);
apiContext.setConfigurationMap(getApiConfig());
return apiContext;
```

We noticed 401s on all our SDK calls, i.e. `Payment.create` and `Payment.list` methods.
We're reverting the sdk version back, but do you have an idea of what it could be caused by?
Also, it did work on the sandbox environment.

**Comment by jaypatel512** [comment] 2016-10-27 21:43
Hey @twiho !

Can you try creating apiContext the recommended way for 1.11.0.

```java
try {
    APIContext context = new APIContext(clientId, clientSecret, "sandbox");
    card.create(context);
    System.out.println(card.toJSON());
} catch (PayPalRESTException e) {
    System.err.println(e.getDetails());
}
```

We did make some changes to APIContext to make them threadsafe. Just wanted to see if this fixes the issue for you. We will try to reproduce the issue you are facing once we get a success using this new method.

Let me know please. Thanks.
