### ISSUE TITLE
No real payment showing up.

### ISSUE THREAD

**Issue by Jerem584** [paypal/PayPal-Java-SDK#344] opened 2018-03-05 21:41 UTC
* SDK/Library version: 
* Environment: Live
* Language, language version, and OS: Java 1.8.0_101 on W10 

Just no payment showing. Only created one.

			PayPalEnvironment environment = new PayPalEnvironment.Live(clientID, clientSecret);
			PayPalHttpClient client = new PayPalHttpClient(environment);
			PaymentListRequest a = new PaymentListRequest();

		    HttpResponse<PaymentHistory> paymentResponse = client.execute(a);
		    PaymentHistory payment = paymentResponse.result();
		    System.out.println(payment.count());
		    for(Payment p : payment.payments())
		    {
		    	System.out.println(p.id());
		    }

Tested with paypal sdk 2.0 & paypal restapi

**Comment by xiaoleih41** [comment] 2018-03-06 18:02
Can you  provide more detail? Did you get any error? do you have a `debugId`? Did you check in the sandbox environment too? What's the result?

**Comment by Jerem584** [comment] 2018-03-07 12:12
Hum Was in LIVE . No error just 4 payment i created.

**Comment by Jerem584** [comment] 2018-03-07 12:14
With a simple program (Payment.create)

With the code i provide you it only show created payment.

If i send 1 EURO to the paypal. The payment won't show up

**Comment by xiaoleih41** [comment] 2018-03-07 15:48
Are you saying you get payment execution success but no payment show up on PayPal? Is it a random issue or a consistent issue? Can you file a ticket with developer.paypal.com/support. If it's a production issue, due to account security, the tech team can do some more account specific troubleshooting.

**Comment by Jerem584** [comment] 2018-03-09 10:11
consistent issues. I just want to show on my programs all the payment, and get one with ID

**Comment by xiaoleih41** [comment] 2018-03-12 14:32
What's the API response after the buyer approves it and you execute the payment? do you have a debugId in the header of the response? Can you reproduce it in sandbox and if it's production issue only. Please close this ticket and file a ticket with developer.paypal.com/support instead.

**Comment by xiaoleih41** [comment] 2018-03-26 15:04
Close this issue due to inactivity. Please resubmit when you have additional info.

**Closed by xiaoleih41** 2018-03-26 15:04 UTC
Labels: question
