### ISSUE TITLE
We can't process your payment right now, so please try again later. We're sorry for the inconvenience.

### ISSUE THREAD

**Issue by avinashpothula** [paypal/PayPal-Java-SDK#326] opened 2017-11-07 14:00 UTC
hi this is avinash i want make transactions with PayaPal _adoptive payments_. i getting this error
> **We can't process your payment right now, so please try again later. We're sorry for the inconvenience.**
i got good response and i got paypal login screen also. but when i make payment it i getting that error
**# Url is =https://www.sandbox.paypal.com/in/cgi-bin/webscr?cmd=_flow&SESSION=ivtQJK_D-2CPIyp9liNi6s_GyiM4BOp1x8FbXbmc6ZPftTjzsMu3m38YKQu&dispatch=5885d80a13c0db1f8e263663d3faee8dc3f308debf7330dd8d0b0a9f21afd7d3&rapidsState=AdaptivePayment_
![screenshot-2017-11-7 error error PayaPal](https://user-images.githubusercontent.com/28857280/32497254-f85e91d2-c3f1-11e7-9421-8367f0c58667.png)
_NewUI__ApprovePayRequestFlow___StateGetFundingSource&rapidsStateSignature=(null)

 any one help me i stuck this problem

**Comment by pp-randy** [comment] 2017-11-07 14:25
Closing as a duplicate of https://github.com/paypal/adaptivepayments-sdk-java/issues/22.

**Closed by pp-randy** 2017-11-07 14:25 UTC
