### ISSUE TITLE
Unable to get note to payee

### ISSUE THREAD

**Issue by sjakobeit** [paypal/PayPal-Java-SDK#60] opened 2015-01-09 07:35 UTC
If a user make a note to a payment during the payment process, where do I find this note vit the rest API?

Payment method is "paypal". Payment intent is "sale".

The note to payee in the transactions is always empty.

**Comment by jaypatel512** [comment] 2015-01-09 07:36
Duplicate of https://github.com/paypal/PayPal-NET-SDK/issues/63

**Closed by jaypatel512** 2015-01-09 07:36 UTC
