### ISSUE TITLE
payment.execute(apiContext,paymentExecution)  getInvoiceNumber is null. 

### ISSUE THREAD

**Issue by bill-brown** [paypal/PayPal-Java-SDK#90] opened 2015-02-27 05:11 UTC
Hello. After a user checks out and approves payment through the paypal site,  I'm not able to retreive the invoice number .  

````java
createdPayment = payment.execute(apiContext, paymentExecution);
````

`createdPayment.getTransactions().get(0).getInvoiceNumber()` returns null.  

This appears to be the same issue affecting the php sdk as well 
https://github.com/paypal/PayPal-PHP-SDK/issues/130

There isn't a work around though because when I change the `payment_type` to "credit_card" instead of "paypal"  I get this error 

 error with paypalResponse Code : 400 with response : 

````json
{
	"name": "VALIDATION_ERROR",
	"details": [{
		"field": "payer",
		"issue": "For credit_card payment method, the supported funding instrument is credit_card or cardit_card_token "
	}],
	"message": "Invalid request - see details",
	"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR",
	"debug_id": "24540e50dd231"
}
````
Is this something in queue to be fixed. 

Thanks.

**Comment by bill-brown** [comment] 2015-02-27 12:52
My workaround for this is to put the invoice number in the return and cancel URL's.  Is there a downside to this?

**Comment by jziaja** [comment] 2015-03-05 16:06
Hi @bill-brown, thanks for reporting this issue!  I was able to reproduce this behavior and am seeing the following behavior for the payment flow:

| Payment funding source | API method invoked | Does response include `invoice_number`? |
| --- | --- | --- |
| PayPal | Create | Yes |
| PayPal | Get _(to check state of resource prior to payment execution)_ | Yes |
| PayPal | Execute | **No** |
| PayPal | Get _(to check state of resource after payment execution)_ | Yes |
| Credit Card | Create | Yes |

Did you try doing a GET on the payment resource after execution?  That should (hopefully) return the `invoice_number` you originally set.

We have an internal ticket (**SRE-23887**) regarding this issue that was closed back in October of last year; however, it was specific to the `invoice_number` not appearing in payment resources for credit card payments.  I'll reopen this ticket with this new information and provide an update here once I have more information to share.

Also, the reason for the 400 error is along with changing the `payment_type` to `credit_card`, you also need to provide the `credit_card` or `credit_card_token` information in the `funding_instruments` list.  Did you also include one of those?

And one last thing, sale payments (`intent` = `sale`) made with a credit card do not require execution.  The credit card payment will automatically be executed when you create the sale payment resource.

**Comment by jziaja** [comment] 2015-03-05 16:10
Also, regarding your question:

> My workaround for this is to put the invoice number in the return and cancel URL's. Is there a downside to this?

Nope, no downside. :)  Feel free to put whatever extra tracking information you might need in the URL.  The generated EC token for the payment will simply be appended to the URL query parameter list.  We do a similar thing with the sample projects so we can properly keep track of the flow before and after the redirect to PayPal.

**Comment by bill-brown** [comment] 2015-03-05 16:15
Hi jziaja

"Did you try doing a GET on the payment resource after execution? That should (hopefully) return the invoice_number you originally set."

No I didn't try a get on the payment resource after execution.  Since my workaround works sufficiently, Id rather use in instead of making another round trip for the invoice.  

I'm glad you are reopening this though and will possibly include it in the payload at a future point because I think it is a little more secure to get the invoice number from the request body than on the url.  

Thanks for your help.

**Comment by jziaja** [comment] 2015-03-05 16:33
Quick update: To help get this in front of the payments team, I opened a new ticket (**PPTIPS-2937**) since the previous ticket was specific to credit card payments.  The two tickets are linked to preserve the history, but hopefully we can get this fix prioritized...  I'll keep you posted once I have more information from them.

**Comment by bill-brown** [comment] 2015-03-05 16:39
ok. thanks. Can you paste the url to PPTIPS-2937?  I wasnt' able to locate it on the web and want other people to be able to see this too.

**Comment by jziaja** [comment] 2015-03-05 16:54
Unfortunately, the ticket number corresponds to a PayPal-internal ticket with no external-facing link.  We share the ticket numbers here just so others have a means of referencing the ticket here on GitHub or with support staff if necessary.

**Comment by juwlee** [comment] 2016-05-10 19:41
For internal tracking: PPPLPAYPT-6883

**Comment by ppmtscory** [comment] 2016-07-12 17:55
The internal changes needed for this to be fixed have been pushed to production.  I now see the `invoice_number` in the Execute response.  Closing.

**Closed by ppmtscory** 2016-07-12 17:55 UTC
Labels: api-enhancement, api-payments
